pr:
- master

pool:
  vmImage: windows-latest

variables:
- group: 'AppCenter-SDK Unity Credentials and Info'
- group: 'appcenter-sdk Internal NuGet feed credentials'
- name: Codeql.Cadence
  value: 0

jobs:
- job:
  displayName: Build and CodeQL PuppetApp Android
  steps:
  - checkout: self
    submodules: recursive

  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize

  - task: AzureKeyVault@2
    displayName: 'Download KeyValult Variables'
    inputs:
      azureSubscription: 'AC - Dev Infra & Build Pool'
      KeyVaultName: 'mobile-center-sdk'
      SecretsFilter: 'appcenter-sdk-unity-serial-number-windows,appcenter-sdk-unity-username,appcenter-sdk-unity-password,appcensk-appcenter-token,appcenter-sdk-blob-storage-access-secret'
      RunAsPreJob: false

  - task: PowerShell@2
    displayName: 'Install Unity'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target="Install-Unity-Windows" -Verbosity="Diagnostic"'

  - task: UseDotNet@2
    displayName: 'Use .Net Core sdk 3.0.100'
    inputs:
      version: 3.0.100

  - task: PowerShell@2
    displayName: 'Activate Unity'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target="RegisterUnity" -UnitySerialNumber="$(appcenter-sdk-unity-serial-number-windows)" -UnityUsername="$(appcenter-sdk-unity-username)" -UnityPassword="$(appcenter-sdk-unity-password)" -Verbosity="Diagnostic"'

  # - task: Bash@3
  #   displayName: 'Restore .meta files'
  #   inputs:
  #     targetType: inline
  #     script: |
  #       # After activating unity, some important .meta files are deleted, so they must be un-deleted
  #       git reset --hard

  # - task: Bash@3
  #   displayName: 'Download gradle'
  #   inputs:
  #     targetType: filePath
  #     filePath: './build.sh'
  #     arguments: '-target=DownloadGradle -GradleUrl="$(GRADLE_URL)" -Verbosity="Diagnostic" '
  #   enabled: false

  - task: PowerShell@2
    displayName: 'Download Android NDK'
    inputs:
      targetType: 'inline'
      script: |
        $NdkUrl = "$(ANDROID_NDK_URL)"
        & ./build.ps1 -target "DownloadNdk" -NdkUrl $NdkUrl -Verbosity "Diagnostic"

  - task: PowerShell@2
    displayName: 'Run Cake Target "BuildPuppetApps"'
    inputs:
      targetType: 'inline'
      script: |
        $NuGetPassword = "$(NUGET_PASSWORD)"
        $NuGetFeedId = "$(NUGET_FEED_ID)"
        $StorageAuthParams = "$(STORAGE_AUTH_PARAMS)"
        & ./build.ps1 -target "BuildPuppetApps" -NuGetPassword $NuGetPassword -NuGetFeedId $NuGetFeedId -Verbosity "Diagnostic" -StorageAuthParams $StorageAuthParams

  - task: PowerShell@2
    displayName: 'Unregister Unity'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target="UnregisterUnity" -UnitySerialNumber="$(appcenter-sdk-unity-serial-number-windows)" -UnityUsername="$(appcenter-sdk-unity-username)" -UnityPassword="$(appcenter-sdk-unity-password)" -Verbosity="Diagnostic"'
    condition: always()

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize
